### ISSUE TITLE
Initil PIN questions

### ISSUE THREAD

**Issue by WillRuddick** [grassrootseconomics/cic-ussd#46]
"Please enter a new four number pin"

Should be 
"Please

n.b. please show @WillRuddick how to make changes to the language CSV

**Comment by PhilipWafula** [comment]
Should be?

The current menu is as follows:

```
English
-----------
1. CON Please enter a new four number PIN for your account.
2. CON Enter your four number PIN again
```

```
Swahili
-----------
1. CON Tafadhali weka pin mpya yenye nambari nne kwa akaunti yako
2. CON Weka PIN yako tena
```

@WillRuddick shall it be reverted to the above ?
