### ISSUE TITLE
Missing voucher from select vouchers

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/cic-ussd#50]
Steps to reproduce:

1. Transfer/mintTo voucher to a custodial account
2. On USSD: `2 > 1` (Select Voucher Menu)
3. Displays:

```
1. undefined undefined
0. Back
11. Next
00. Exit
```

Possible issue:

The hydration ultimately relies on a func named `generateSymbolMap` which attempts to build vouchers held based on the last 9 transactions via `getFullGraphUserData` thru the transactions array.

Possible fix: 

State re-hydration needs to run every time against the user and **all-time** transactions.

A sample GraphQL query could be:

```graphql
query MyQuery {
  transactions(where: {_or: [{recipient_address: {_eq: "$BLOCKCHAIN_ADDRESS"}}, {recipient_address: {_eq: "$BLOCKCHAIN_ADDRESS"}}]}, distinct_on: voucher_address) {
    voucher {
      symbol
      voucher_name
    }
  }
}
```

**Comment by kamikazechaser** [comment]
After sometime it does get rehydrated. But selection does fail.

**Comment by PhilipWafula** [comment]
This was fixed here, at least partially: https://github.com/grassrootseconomics/cic-ussd/pull/49/commits/ba191acef0b47d15805d909d3b5bb31f1f893336

I noticed that if you create an account and don't receive any transaction, the held vouchers aren't updated hence the issue.

**Comment by PhilipWafula** [comment]
Though I'd like to watch a mint and see how it behaves. I am not sifting through tx types so I am curious why it would seem to be missing the tx altogether
